name = "Imperfect Feynman"
license = "MIT"
licenselink = "https://github.com/bcokert/hugo-future-imperfect/blob/master/LICENSE.md"
description = "Customized theme originally based on julio pescador's Future Imperfect"
homepage = "https://github.com/bcokert/hugo-future-imperfect"
tags = ["blog", "responsive", "font awesome", "highlight.js"]
features = ["html5", "css3", "responsive", "compact"]
min_version = 0.15

[author]
  name = "Brandon Okert"
  homepage = "http://brandonokert.com"

[original]
  name = "Hugo Future Imperfect"
  homepage = "https://github.com/jpescador/hugo-future-imperfect"
  repo = "jpescador/hugo-future-imperfect.git"
